---
# tasks file for csrs


- name: Create a directory if it does not exist csrs 
  file:
    path: /home/ubuntu/mongodb/db/{{item.csrs_name}}
    state: directory

- name: setup the configuration files
  template:
    src: csrs.j2
    dest: /home/ubuntu/{{item.csrs_name}}.conf
    owner: ubuntu
    group: ubuntu

- name: Check if port 26011 is already in use
  shell: netstat -tuln | grep :{{item.csrs_port}}
  register: port_check
  changed_when: false
  ignore_errors: yes
  failed_when: False

# - name: printing output of the port
#   debug:
#     var: port_check

- name: lets start the mongod nodes
  command: mongod -f /home/ubuntu/{{item.csrs_name}}.conf
  when: port_check.rc != 0
  
- name: copying configuration file
  template:
    src: user_config.j2
    dest: /home/ubuntu/config.js
  when: inventory_hostname == 'csrs1'

- name: executing config.js (initilize replica and username & password)
  shell: mongosh --port {{item.csrs_port}} --eval < /home/ubuntu/config.js
  when: inventory_hostname == 'csrs1'

- name: copying configuration file
  template:
    src: replicaset_node.j2
    dest: /home/ubuntu/config.js
  when: inventory_hostname == 'csrs1'

- name: Create MongoDB Admin User
  shell: mongosh --host {{item.csrs_name}}/{{PRI_IP_ADD}}:{{item.csrs_port}} -u "{{user_name}}" -p "{{user_password}}" --authenticationDatabase "admin" --eval < /home/ubuntu/config.js
  when: inventory_hostname == 'csrs1'
  register: data

